# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5EwDnxz2DsJZ_OH5CN-SVR-6DvW0SJm
"""

import pandas as pd

df = pd.read_csv("marketing_campaign.csv", sep="\t")


df['Income'].fillna(df['Income'].median(), inplace=True)


df.drop_duplicates(inplace=True)

df['Education'] = df['Education'].str.strip().str.lower().replace({
    '2n cycle': 'master',
    'graduation': 'graduate',
    'phd': 'phd',
    'master': 'master',
    'basic': 'basic'
})

df['Marital_Status'] = df['Marital_Status'].str.strip().str.lower().replace({
    'married': 'married',
    'together': 'married',
    'single': 'single',
    'divorced': 'divorced',
    'widow': 'widowed',
    'alone': 'single',
    'absurd': 'single',
    'yolo': 'single'
})


df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True)


df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df = df.astype({
    'year_birth': 'int64',
    'income': 'float64'
})


df.to_csv("marketing_campaign_cleaned.csv", index=False)

print("✅ Preprocessing complete. Cleaned dataset saved as marketing_campaign_cleaned.csv")